// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cokzjkjppfrnnrswxllk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNva3pqa2pwcGZybm5yc3d4bGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTQ5NTgsImV4cCI6MjA1Nzk5MDk1OH0._HZjNK8ng93WsH222HWuiGD63NjdOUk4zYy-t-wZ3iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);